x-modeling-common: &modeling-common
  working_dir: /app
  image: anomaly-detection/modeling:latest
  environment: &common-environment
    CATEGORY: ${CATEGORY}
    DATA_CLEAN_DB: ${DATA_CLEAN_DB}
    DATA_TRAIN_DB: ${DATA_TRAIN_DB}
    DATA_TEST_DB: ${DATA_TEST_DB}
    DATA_TRAIN_DIR: ${DATA_TRAIN_DIR}
    DATA_TEST_DIR: ${DATA_TEST_DIR}
    DATA_TEST_PATCHING_DIR: ${DATA_TEST_PATCHING_DIR}
    REPORTS_CONFIG: ${REPORTS_CONFIG}
    REPORTS_REPORT: ${REPORTS_REPORT}
    REPORTS_MODEL: ${REPORTS_MODEL}
    MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
  networks:
    - mlflow
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    init-modeling:
      condition: service_completed_successfully

x-flags: &default-flags
  PYTHONUNBUFFERED: 1
  TF_CPP_MIN_LOG_LEVEL: 1
  GIT_PYTHON_REFRESH: silent

services:
  init-modeling:
    image: anomaly-detection/modeling:latest
    build:
      context: ./apps/modeling/
    volumes:
      - raw-data:/data
    command: chown -R ${AIRFLOW_UID:-50000}:0 /data

  load-initial-models:
    <<: [*modeling-common]
    command: .venv/bin/load_initial_models
    volumes:
      - ${MODELS_PATH}:/app/models:ro
    environment:
      <<: [*default-flags]
      MODELS_PATH: ./models
      MODELS_CONFIG: ${MODELS_CONFIG}
      MODELS_REPORT: ${MODELS_REPORT}
      MODELS_MODEL: ${MODELS_MODEL}
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
    networks:
      - mlflow

  load-raw-data:
    <<: [*modeling-common]
    command: .venv/bin/load_raw_data
    volumes:
      - raw-data:/app/${S3_DATA_RAW_PATH}:rw
      - ${DATA_PATH}:/app/data/processed:rw
    environment:
      <<: [*common-environment, *default-flags]
      DATA_PATH: ./data/processed
      S3_ENDPOINT: ${S3_ENDPOINT}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_CLEAN_DB_FILE: ${S3_CLEAN_DB_FILE}
    networks:
      - minio

  load-config:
    <<: [*modeling-common]
    command: .venv/bin/load_config
    volumes:
      - ${CONFIG_FILE}:/app/config.json:rw
      - ${REPORTS_PATH}:/app/reports:rw
    environment:
      <<: [*common-environment, *default-flags]
      CONFIG_FILE: config.json
      CONFIG_FROM_MODEL_REGISTRY: ${CONFIG_FROM_MODEL_REGISTRY}
      CONFIG_FROM_MODEL_REGISTRY_ALIAS: ${CONFIG_FROM_MODEL_REGISTRY_ALIAS}
      REPORTS_PATH: ./reports

  preprocess-data:
    <<: [*modeling-common]
    command: .venv/bin/preprocess_data
    configs:
      - source: config
        target: /app/config.json
    volumes:
      - raw-data:/app/${S3_DATA_RAW_PATH}:ro
      - ${DATA_PATH}:/app/data/processed:rw
      - ${REPORTS_PREPROCESSING_PATH}:/app/reports:rw
    environment:
      <<: [*common-environment, *default-flags]
      CONFIG_FILE: config.json
      DATA_PATH: ./data/processed
      REPORTS_PREPROCESSING_PATH: ./reports

  train-model:
    <<: [*modeling-common]
    command: .venv/bin/train_model
    configs:
      - source: config
        target: /app/config.json
    volumes:
      - ${DATA_PATH}:/app/data/processed:ro
      - ${REPORTS_PREPROCESSING_PATH}:/app/reports_preprocessing:ro
      - ${REPORTS_TRAINING_PATH}:/app/reports:rw
    environment:
      <<: [*common-environment, *default-flags]
      CONFIG_FILE: config.json
      DATA_PATH: ./data/processed
      REPORTS_PREPROCESSING_PATH: ./reports_preprocessing
      REPORTS_TRAINING_PATH: ./reports
      MAX_EPOCHS: ${MAX_EPOCHS}

  evaluate-model:
    <<: [*modeling-common]
    command: .venv/bin/evaluate_model
    configs:
      - source: config
        target: /app/config.json
    volumes:
      - raw-data:/app/${S3_DATA_RAW_PATH}:ro
      - ${DATA_PATH}:/app/data/processed:ro
      - ${REPORTS_TRAINING_PATH}:/app/reports_training:ro
      - ${REPORTS_EVALUATION_PATH}:/app/reports:rw
    environment:
      <<: [*common-environment, *default-flags]
      CONFIG_FILE: config.json
      DATA_PATH: ./data/processed
      REPORTS_TRAINING_PATH: ./reports_training
      REPORTS_EVALUATION_PATH: ./reports

configs:
  config:
    file: ${REPORTS_PATH}/${REPORTS_CONFIG}

networks:
  mlflow:
    external: true
  minio:
    external: true

volumes:
  raw-data:
    name: raw-data-${CATEGORY}