services:
  prediction:
    container_name: prediction-api
    working_dir: /app
    build:
      context: ./apps/prediction/
    ports:
      - $PREDICTION_PORT:8000
    volumes:
      - $MODELS_PATH:/app/$VIRTUAL_MODELS_PATH:ro
      - $MONITORING_REPORTS_PATH:/app/$VIRTUAL_MONITORING_REPORTS_PATH
    environment:
      - MODELS_DIR=$VIRTUAL_MODELS_PATH
      - MONITORING_EVENTS_FILE=$VIRTUAL_MONITORING_REPORTS_PATH/$MONITORING_EVENTS_FILE
      - MLFLOW_MODEL_NAME=$MLFLOW_MODEL_NAME
      - MLFLOW_MODEL_VERSION=$MLFLOW_MODEL_VERSION
      - MLFLOW_RUN_ID=$MLFLOW_RUN_ID
      - LOG_LEVEL=$LOG_LEVEL
      - PYTHONUNBUFFERED=1
      - TF_CPP_MIN_LOG_LEVEL=1
