{
 "title": "API Traffic & Performance",
 "tags": [
  "monitoring",
  "api"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Timer duration per request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(prediction_request_duration_seconds_bucket{method=\"POST\",path=\"/predict/{category}\"}[30s])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total prediction requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prediction_requests_total{method=\"POST\",path=\"/predict/{category}\"}[$__range]))",
     "legendFormat": "total rps"
    }
   ]
  },
  {
   "title": "Mean predict latency (5m)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(prediction_request_duration_seconds_sum{method=\"POST\",path=\"/predict/{category}\"}[5m])) / clamp_min(sum(rate(prediction_request_duration_seconds_count{method=\"POST\",path=\"/predict/{category}\"}[5m])), 1e-9)\r\n\r\n"
    }
   ]
  },
  {
   "title": "Predictions by category",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (category) (\r\n  increase(prediction_inference_total{job=\"prediction-api\"}[$__range])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(prediction_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(prediction_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Status API",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{job=\"prediction-api\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}