groups:
  - name: data-behavior
    rules:
      - alert: InputDataDriftHigh
        expr: evidently_data_drift_score{category="all"} > 0.5
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: "Input data drift score is high"

      - alert: DataQualityIssuesRateHigh
        expr: evidently_data_quality_issues_rate{category="all"} > 0.05
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: "Data quality issues rate is high"
